### ISSUE TITLE
Error al utilizar la función de FuncionHurwicz.R para valores de alpha menores o iguales que 1

### ISSUE THREAD

**Issue by marparven1** [AlvaroBlazquezMolino/TD-Tarea-1#1]
Buenas chicos, he tratado de resolver mi función con la nueva propuesta que ha creado Álvaro pero he obtenido el siguiente error al compilar:
 **Error in Alt_vHurwicz[i] <- which.min(vAltH) : 
  replacement has length zero**

He mirado el código y he llegado a la siguiente conclusión, si alpha es menor o igual a 1, en vez de usar un vector con una única componente, alpha,

**if (alfa<=1) {
      valfa = c(alfa);
    } else {
      valfa = seq(from=0,to=1,by=(1/alfa)); ## alfa: 100, 200,
    }**

Planteo la posibilidad de crear una secuencia, al igual que hacemos en el caso de alpha mayor estricto que uno, así la función va recorriendo la secuencia.

** if (alfa<=1) {
      valfa = seq(from=0,to=1,by=(alfa)); ## alfa: 100, 200,
    } else {
      valfa = seq(from=0,to=1,by=(1/alfa)); ## alfa: 100, 200,
    } **

En este caso sí me ha funcionado perfectamente la función.

**NOTA**: HAY QUE CAMBIARLO DOS VECES, PARA FAVORABLE Y PARA NO FAVORABLE (LÍNEAS 9 Y 42 DEL CÓDIGO)

También he pensado lo siguiente, porqué no usar si alpha es menor que uno una secuencia pero de la siguiente forma:

  valfa = seq(from=0,to=1,by=0.01); ó    valfa = seq(from=0,to=1,by=0.05);

¿Qué os parece?

He creado un fichero R llamado **FuncionHurwiczEditada.R** donde he cambiado la función con lo que he pensado, a ver que os parece. Haré un push para que podáis tener acceso a ella.

**Comment by AlvaroBlazquezMolino** [comment]
Es buena idea, me gusta la primera alternativa pero ¿cómo se comportaría si alfa no es múltiplo entero de 1 (por ejemplo, 0,3 en lugar de 0,1 o 0,05)?

**Comment by marparven1** [comment]
Alvaro, respondiendo a lo que planteas, R al crear una secuencia desde A hasta B, parará al llegar a B. Me explico, si no es un múltiplo entero de 1, parará justo en el múltiplo anterior antes de llegar a 1.

Lo ilustro con varias secuencias sencillas definidas en la consola de R:

> seq(0,1,0.3)
[1] 0.0 0.3 0.6 0.9
> seq(0,1,0.6)
[1] 0.0 0.6

> seq(0,1,0.01)
  [1] 0.00 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.10 0.11 0.12 0.13 0.14
 [16] 0.15 0.16 0.17 0.18 0.19 0.20 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29
 [31] 0.30 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.40 0.41 0.42 0.43 0.44
 [46] 0.45 0.46 0.47 0.48 0.49 0.50 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59
 [61] 0.60 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.70 0.71 0.72 0.73 0.74
 [76] 0.75 0.76 0.77 0.78 0.79 0.80 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89
 [91] 0.90 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.00

Por tanto, creo que no es incorrecto dejarlo así, como la función editada.

**Comment by AlvaroBlazquezMolino** [comment]
Cierto, lo probé con alfa = 0,3 que venía por defecto y actuaba así, perfecto!
